
# Travis Build Multiple Docker Images from a Single Repo
# https://stackoverflow.com/questions/39422135/travis-build-multiple-docker-images-from-a-single-repo

sudo: required

matrix:
      
services:
  - docker

env:

before_install:

install:

before_script: 

script:
  - echo ' -----------------  BUILD PART 1 ----------------- '
  - echo 'docker bulid...' && cd flask_mysql_postgre_infra && docker-compose up -d && docker-compose stop


after_script:  

after_success:

after_failure:

before_deploy:

deploy:

after_deploy: