sudo: required

matrix:

services:
  - docker

env:

script:
  # docker build 
  - echo ' -----------------  BUILD DOCKER IMAGES  ----------------- ' && bash build.sh

before_deploy:
  #- echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin && echo "docker login OK" || echo "docker login failed"

deploy:
  # docker commit and push 
  REGISTRY_USER: $REGISTRY_USER
  REGISTRY_PASS: $REGISTRY_PASS
  script: echo '----------------- DEPLOY TO DOCKER HUB -----------------' && (echo "$REGISTRY_PASS" && echo "$REGISTRY_USER" && export REGISTRY_PASS=$REGISTRY_PASS && export REGISTRY_USER=$REGISTRY_USER) && bash deploy_dockerhub.sh
  on:
    branch: master

after_deploy: