sudo: required

services:
  - docker

branches:
  only:
  - master

script:
  - echo ' -----------------  BUILD DOCKER IMAGES  ----------------- '
  - bash build.sh

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin && echo "docker login OK" || echo "docker login failed"

deploy:
   - echo '----------------- DEPLOY TO DOCKER HUB -----------------'
  - bash deploy_dockerhub.sh 
  on:
    branch: master

after_deploy: