sudo: required

matrix:

services:
  - docker

env:

script:
  - echo ' -----------------  BUILD DOCKER IMAGES  ----------------- '
  - bash build.sh

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin && echo "docker login OK" || echo "docker login failed"

deploy:
  provider: script
  # docker commit and push 
  script: echo '----------------- DEPLOY TO DOCKER HUB -----------------'
  on:
    branch: master

after_deploy: