version: '2'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
    database:
        hostname: mongo
        image: mongo:latest
        ports:
            - "27018:27017"