zeppelin:
  image: dylanmei/zeppelin
  environment:
    ZEPPELIN_PORT: 8080
    ZEPPELIN_JAVA_OPTS: >-
      -Dspark.driver.memory=1g
      -Dspark.executor.memory=2g
    SPARK_SUBMIT_OPTIONS: >-
      --conf spark.driver.host=localhost
      --conf spark.driver.port=8081
      --conf spark.es.nodes=elasticsearch
      --conf spark.es.discovery=false
      --conf spark.es.port=9200
      --packages org.elasticsearch:elasticsearch-spark-20_2.11:5.0.0-alpha5
    MASTER: local[*]
    ELASTICSEARCH_HOST: elasticsearch
    ELASTICSEARCH_PORT: 9300
  links:
    - elasticsearch:elasticsearch
  ports:
    - 8080:8080
    - 8081:8081
    - 4040:4040
  volumes:
    - ./notebooks:/usr/zeppelin/notebook
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  ports:
    - 9200:9200
    - 9300:9300
kibana:
  image: docker.elastic.co/kibana/kibana:6.3.2
  links:
    - elasticsearch:elasticsearch
  ports:
    - "5601:5601"