# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081